name: Build and Deploy Locally
on:
  push:
    branches: ["main"]
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build local Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
      - name: Deploy with Docker Compose
        run: |
          docker compose down
          docker compose down --remove-orphans
          docker compose up -d --build
